sudo: false
language: node_js

node_js:
    - 8
    - 10
    - 12

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c75729ddc58d8813cc6d
    on_success: always
    on_failure: always
    on_start: never

before_script:
  - npm run build

after_script:
  - npm run coveralls
